### ISSUE TITLE
Cannot pass className inside props

### ISSUE THREAD

**Issue by antoinekm** [nusu/avvvatars#11]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/54948363/161558994-343a715b-d4b1-481c-b8e9-8275a72a83f8.png">

I would like to be able to pass a className into Params

**Comment by nusu** [comment]
That's not possible at the moment but you can tweak it. Wrap the component around a div
```
<div class="avatar-wrapper">
	<Avvvatars value="something" />
</div>
```

then apply styles like this:
```
	.avatar-wrapper > div {
		background-color: #000;
	}
```

that should do the trick
